name = "launchlayer-subscribe"
type = "javascript"
compatibility_date = "2024-06-01"

[vars]
SHEET_ID = "16ZVu7f-1nnsOdH5qz-UFrVu-wU9WJWL3KuDWuB55NCg"
CLIENT_EMAIL = "launchlayernews@launchlayer-subscriber-api.iam.gserviceaccount.com"
PRIVATE_KEY = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCLYsLyqN0flamK
DrtF0JBRqM4m6kbXNq7weY2zUsTEaENJavvKDTW11SW1nG6w53lEvevj0NYt9yod
mO91lUNhbp0jxpsmzWW1QGCEwGER1JyEAJTadm+DezYoA17qfhzBnNZkzgwmOcsi
CeNUXxT0cjUvYWHeEClXkAFe8DfqLdUP0/MGjXrWLijMarRqJWW6Ul7DprEz+srf
tvPRqf/Dd9TztA25wmt7U2V8Fh/AmsLfvIkoHDADkEGCO0Y884wW+knH2DfTzEZJ
xB2Qo29eL0jbid9LhtFl/GrFwNor38AStT1fYswhv/NFcOFx+1nJcYN1Qqj9+xRF
3ZBFXkV3AgMBAAECggEAHFy+zXDF+fDSvEhuG/EqBKvEMw/11UIHy9/4EPa1GkAa
/Pv7eyw/8x2JnFBWB8I6H15D+ynaAyVpmPcvNq5mNRO0fvyhQn6GBSEx4qFgvyeT
p5qUr3VtEISISxEQhceeo1j+GSoCN98HsgfwDZGBapI4t0jqCK0iNHKVjNN1lT1s
WKCNOzGFDO9WMuoDxxuI16YPfuYrcczWiNMCD9PCUDRX3W36RRRUJsFFA5OYU34g
oMIG2cJB9Q6LHMkNkC33LQdQob5uy5+tYck1mA3wgT0br9T11zzzVzy1UkOMg389
EcrCAza1CNwUL1zi9y6h56zxRTyuLnMYZeEdA0MyJQKBgQDBpb77g5UgXvQuwr5U
RoGB9qU8pWrpkizvmEAD1rG1m8ngBoDch9hoOv4DUC492/Oviwgsw6K1u3zO07lG
h2uw4rnLnZZKhHV71QlDqUOiUAK5ZaDR973hrgHk5AVwYLT6jy6Mqm4mdq7Gwrhg
+lCZQjEBQRypYsJs39rFzqZn3QKBgQC4REGkBQill/WV00Ppex+9RWatji/Bhywx
dd9LOe3zDzg9edbe28Qm6uFQYQMJys4P4yIAdnW9Xl0QlE0HKaIDyVNSZ5cfOvZJ
u2RQX05cB8KYVKiV6zustVaNPBWuZwMZk4omQm60q1fgCAg158tKAq5m9bsQVXu7
EPCQxRhXYwKBgQC0iX5gpvBlWaF15wHjOEiNjhHHVME0OZ/DUMJ90a+kjTXMssN4
1v2fT0B6fkpeSa4LPyfD9DDCFaXqfeICK0bvhrGJb8Yqewu9A4S7nBb+QHIJvwIM
P1i8CqqhZyTa/I49+zd+1XYUThnsHKYhY7245MkjTj0WfoidUKZ6PItP0QKBgQCn
Wg6Hqa61vnJkFZDrP1CPNLXRUH6c9Gg1r4kSKFWs15jLdJmqo8vdUJs7xi/dN9y4
Xx/lbbD3QPmi8h2XML+dUr6i68Q7r/A4/MFZoYVoXf/lG5ZVOmRjMfqeoQBL+fC9
zNq+br1exvMzW/ghBRkDabX9epXfetO6DON/iBHYYwKBgFpSDhOWWJSnphOSL+Lw
BjYWJ3Fbv9UbpLZf4OGPXc7kN95nG0+fMX8Qi3ZR/ayVGAVgN+hHfjmx/+/pgcqm
HHs+LZMJhohNdO/qhrF6qRjfL842r7asGRohuHsgrC0iJcuc+zz8q/tG8HYLUoYD
aUlWD2yFUaxVOLz2Jf1wJCYT
-----END PRIVATE KEY-----"""
